### PR TITLE
Created a Notes App

### PR DESCRIPTION
**Pull request by vivek9386**

### CODE REVIEW

**Comment by vivek9386** [comment]
vivek9386-Notes-#148

**Comment by anshulkhattar** [comment]
@vivek9386 please add your name to Contributors list.

**Comment by vivek9386** [comment]
i have added my name to the contributors list and updated readme file as well but it is having merge conflicts.

**Comment by anshulkhattar** [comment]
ReadMe has been changed. 
Please don't change the repository readme to describe your own project. 
Take a pull from repository. Change the ReadMe of your individual project to whatever you want. Don't alter repository's readme.

**Pull request closed without merging**
